version: "3.8"
  
services:
  server:
    build: ./server/
    env_file: .env
    volumes:
      - logs:/app/logs/
    ports:
      - "50051:50051"
    depends_on:
      - db

  client:
    build: ./client/
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/server/
    depends_on:
      - db
      - server

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes: 
  pg_data:
  logs: