# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: investment.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'investment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10investment.proto\x12\x05order\"2\n\x11\x43ustomErrorDetail\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\r\n\x05\x66ield\x18\x02 \x01(\t\"7\n\x07Payment\x12\x15\n\rpaymentNumber\x18\x01 \x01(\x05\x12\x15\n\rpaymentAmount\x18\x02 \x01(\x01\"p\n\x10InvestmentResult\x12\x14\n\x0cinvestorName\x18\x01 \x01(\t\x12\x1d\n\x15totalInvestmentAmount\x18\x02 \x01(\x01\x12\'\n\x0fpaymentSchedule\x18\x03 \x03(\x0b\x32\x0e.order.Payment\"\x90\x01\n\x11InvestmentRequest\x12\x18\n\x10investorFullName\x18\x01 \x01(\t\x12\x16\n\x0einitialDeposit\x18\x02 \x01(\x03\x12\x14\n\x0cinterestRate\x18\x03 \x01(\x01\x12\x18\n\x10investmentPeriod\x18\x04 \x01(\x05\x12\x19\n\x11\x63ompoundFrequency\x18\x05 \x01(\t\";\n\x10\x43ustomFieldError\x12\'\n\x05\x65rror\x18\x01 \x03(\x0b\x32\x18.order.CustomErrorDetail\"\x83\x01\n\x12InvestmentResponse\x12\x33\n\x10investmentResult\x18\x01 \x01(\x0b\x32\x17.order.InvestmentResultH\x00\x12.\n\x0b\x65rrorDetail\x18\x02 \x01(\x0b\x32\x17.order.CustomFieldErrorH\x00\x42\x08\n\x06result2U\n\nInvestment\x12G\n\x10\x43reateInvestment\x12\x18.order.InvestmentRequest\x1a\x19.order.InvestmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'investment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERRORDETAIL']._serialized_start=27
  _globals['_CUSTOMERRORDETAIL']._serialized_end=77
  _globals['_PAYMENT']._serialized_start=79
  _globals['_PAYMENT']._serialized_end=134
  _globals['_INVESTMENTRESULT']._serialized_start=136
  _globals['_INVESTMENTRESULT']._serialized_end=248
  _globals['_INVESTMENTREQUEST']._serialized_start=251
  _globals['_INVESTMENTREQUEST']._serialized_end=395
  _globals['_CUSTOMFIELDERROR']._serialized_start=397
  _globals['_CUSTOMFIELDERROR']._serialized_end=456
  _globals['_INVESTMENTRESPONSE']._serialized_start=459
  _globals['_INVESTMENTRESPONSE']._serialized_end=590
  _globals['_INVESTMENT']._serialized_start=592
  _globals['_INVESTMENT']._serialized_end=677
# @@protoc_insertion_point(module_scope)
